name: Standard CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-build-test-deploy:
    name: Build, Test, Lint & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Lint
        run: npm run lint

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Deploy
        run: npm run deploy
